#---- config ----#
data_base_dir: "C://Users//Jessica//Documents//Proyecto_ssd//Classifier//datasets//20bn-sth-sth-v2"
train_filename: "78-classes_train.json"
validation_filename: "78-classes_validation.json"
models_folder: "./trained_models/"
exp_name : "20sth_sth_v2" #summary writer name, code appends date and time
output_dir: "./outputs"
n_epochs: 30

#data loader
dataset:
  base_dir: ${data_base_dir}
  n_frames : 8 #frames to pick from each video
  str2id_file: "78-classes_labels.json"

dataloader:
  num_workers: 2
  batch_size : 4 #28
  pin_memory: True
  #shuffle: True #RandomSampler shuffles data and its mutex with shuffle
  
#Optimizer
optim:
  lr: 0.0005
  weight_decay: 1e-4

defaults:
  - model: FrameLSTM #ResNetLSTM, FrameLSTM is with "hotspots from video arch."
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

#-- Hydra config --#
hydra:
  run:
    dir: ./${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S} # Output directory for normal runs
